dist: trusty
language: go
go_import_path: github.com/coreos/gofail
sudo: false

go:
  - 1.10.1
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

script:
  - make test
  - make all
